export const INTERNAL_SCHEMA = [
  'NO',
  'PICTURE',
  'NAME',
  'CARTON_QTY',
  'PCS',
  'PRICE',
  'TOTAL_PRICE',
  'cbm',
  'cbms',
  'kg',
  'kgs',
  'السعر بالاوقية',
  'نسبة المكتب',
  'الشحن',
  'سعر الطياح',
];

export const INTERNAL_TO_DB_FIELD = {
  NO: 'no',
  PICTURE: 'picture',
  NAME: 'name',
  CARTON_QTY: 'cartonQty',
  PCS: 'pcs',
  PRICE: 'price',
  TOTAL_PRICE: 'totalPrice',
  cbm: 'cbm',
  cbms: 'cbms',
  kg: 'kg',
  kgs: 'kgs',
  'السعر بالاوقية': 'السعر_بالاوقية',
  'نسبة المكتب': 'نسبة_المكتب',
  'الشحن': 'الشحن',
  'سعر الطياح': 'سعر_الطياح',
};
